sudo: required
language: python
python:
    - "3.5"
services:
  - elasticsearch

cache: pip


before_install:
  - curl -O https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.4.3/elasticsearch-2.4.3.deb \
   && sudo dpkg -i --force-confnew elasticsearch-2.4.3.deb && sudo service elasticsearch restart


install: "pip install -r requirements.txt"

before_script:
  - sleep 10

script: 
    - coverage run ./manage.py test
    - coverage report -m 

after_success:
  - coveralls
