# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 10:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='Username')),
                ('student_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='StudentId')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='BirthDay')),
                ('first_name', models.CharField(default='', max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(default='', max_length=50, verbose_name='Last name')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone Number')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, verbose_name='active status')),
                ('date_joined', models.DateTimeField(auto_now=True, verbose_name='join date')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'users',
                'verbose_name': 'user',
            },
        ),
        migrations.CreateModel(
            name='BarCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar_code', models.CharField(max_length=100, verbose_name='Bar Code')),
                ('is_borrowed', models.BooleanField(default=False, verbose_name='borrowed')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('author', models.CharField(max_length=100, verbose_name='Author')),
                ('publisher', models.CharField(max_length=100, verbose_name='Publisher')),
                ('call_number', models.CharField(max_length=100, verbose_name='Call Number')),
                ('ISBN', models.CharField(max_length=100, verbose_name='ISBN')),
            ],
        ),
        migrations.CreateModel(
            name='BorrowInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_time', models.DateTimeField()),
                ('due_time', models.DateTimeField()),
                ('barcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.BarCode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='barcode',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Book'),
        ),
    ]
